const assert = require("node:assert/strict");
const { parseModelJson, sanitizeAssignments, assignmentResults, mappingResults, unsupportedResponseFormat } = require("../ai-proxy/server.js");

assert.deepEqual(parseModelJson('```json\n{"assignments":[]}\n```'), { assignments: [] });
assert.equal(unsupportedResponseFormat({ error: { message: "This response_format type is unavailable now" } }), true);
assert.equal(unsupportedResponseFormat({ error: { message: "missing or invalid API key" } }), false);
const rangeField = { key: "salary", index: 0, label: "期望月薪", options: ["2001～4000", "4001～6000"] };
assert.deepEqual(sanitizeAssignments({ assignments: [{ key: "salary", index: 0, label: "期望月薪", value: "3500", confidence: 0.9 }] }, [rangeField]), []);
assert.equal(sanitizeAssignments({ assignments: [{ key: "salary", index: 0, label: "期望月薪", value: "2001～4000", confidence: 0.9 }] }, [rangeField])[0].value, "2001～4000");
const semanticField = { key: "industry", index: 0, label: "期望从事行业", options: ["互联网/电子商务", "机械制造"] };
assert.equal(sanitizeAssignments({ assignments: [{ key: "industry", index: 0, label: "期望从事行业", value: "互联网", confidence: 0.9 }] }, [semanticField])[0].value, "互联网/电子商务");
assert.deepEqual(sanitizeAssignments({ assignments: [{ key: "industry", index: 0, label: "期望从事行业", value: "互联网金融", confidence: 0.9 }] }, [semanticField]), []);
const ambiguousField = { key: "job", index: 0, label: "期望从事职业", options: ["前端开发工程师", "前端开发实习生"] };
assert.deepEqual(sanitizeAssignments({ assignments: [{ key: "job", index: 0, label: "期望从事职业", value: "前端开发", confidence: 0.9 }] }, [ambiguousField]), []);
assert.equal(assignmentResults({ assignments: [{ key: "job", index: 0, label: "期望从事职业", value: "前端开发", confidence: 0.9 }] }, [ambiguousField])[0].reason, "not-a-page-option");
const pageCandidateField = { key: "city", index: 0, label: "期望工作城市", type: "combobox", optionSource: "popup", options: ["广州市", "深圳市"] };
assert.equal(sanitizeAssignments({ assignments: [{ key: "city", index: 0, label: "期望工作城市", value: "深圳市", confidence: 0.9 }] }, [pageCandidateField])[0].value, "深圳市");
assert.equal(assignmentResults({ assignments: [{ key: "city", index: 0, label: "期望工作城市", value: "珠海市", confidence: 0.9 }] }, [pageCandidateField])[0].reason, "not-a-page-option");
assert.equal(sanitizeAssignments({ assignments: [{ key: "city", index: 0, label: "期望工作城市", value: "深圳", confidence: 0.7 }] }, [{ key: "city", index: 0, label: "期望工作城市", options: ["广州", "深圳"] }])[0].value, "深圳");
assert.equal(assignmentResults({ assignments: [{ key: "city", index: 0, label: "期望工作城市", value: "深圳", confidence: 0.6 }] }, [{ key: "city", index: 0, label: "期望工作城市", options: ["广州", "深圳"] }])[0].reason, "accepted");
assert.equal(assignmentResults({ assignments: [] }, [{ key: "city", index: 0, label: "期望工作城市", options: ["广州", "深圳"] }])[0].reason, "ai-no-assignment");
const unreadChoice = { key: "city", index: 0, type: "combobox", label: "期望城市", optionSource: "popup-not-found", options: [] };
assert.equal(assignmentResults({ assignments: [{ key: "city", index: 0, label: "期望城市", value: "深圳", confidence: 0.9 }] }, [unreadChoice])[0].reason, "candidate-not-read");
const proficiencyField = { key: "skill", index: 0, label: "掌握程度", options: ["了解", "一般", "熟练", "精通"] };
assert.equal(sanitizeAssignments({ assignments: [{ key: "skill", index: 0, label: "掌握程度", value: "熟悉", confidence: 0.9 }] }, [proficiencyField])[0].value, "熟练");
const speakingField = { key: "speaking", index: 0, label: "听说", options: ["一般", "良好", "熟练", "精通"] };
assert.equal(sanitizeAssignments({ assignments: [{ key: "speaking", index: 0, label: "听说", value: "熟悉", confidence: 0.9 }] }, [speakingField])[0].value, "熟练");
assert.equal(assignmentResults({ assignments: [{ key: "speaking", index: 0, label: "听说", value: "母语", confidence: 0.9 }] }, [speakingField])[0].reason, "not-a-page-option");
assert.deepEqual(sanitizeAssignments({ assignments: [{ key: "speaking", index: 0, label: "听说", value: "掌握", confidence: 0.9 }] }, [{ ...speakingField, options: ["熟练", "熟悉"] }]), []);
const locationField = { key: "location", index: 0, type: "combobox", label: "所在地点", options: ["中国大陆", "广东"], locationCandidates: [{ key: "currentResidence", label: "现居住地", value: "广东省广州市" }] };
assert.equal(sanitizeAssignments({ assignments: [{ key: "location", index: 0, label: "所在地点", value: "广东省广州市", confidence: 0.9 }] }, [locationField])[0].value, "广东省广州市");
assert.equal(assignmentResults({ assignments: [{ key: "location", index: 0, label: "所在地点", value: "广东", confidence: 0.9 }] }, [locationField])[0].reason, "not-a-location-candidate");
const textField = { key: "opaque-text", type: "text", sources: [{ path: "education[1].major" }], isChoice: false };
const mapped = (item) => mappingResults({ assignments: [{ key: textField.key, confidence: 0.95, ...item }] }, [textField])[0];
assert.equal(mapped({ profilePath: "education[1].major", value: "模型捏造的文本" }).assignment.value, "");
assert.equal(mapped({ profilePath: "education[0].major" }).reason, "invalid-profile-path");
assert.equal(mapped({ key: "expired", index: 0, profilePath: "education[1].major" }).reason, "ai-no-assignment");
assert.equal(mappingResults({ assignments: [{ key: textField.key }, { key: textField.key }] }, [textField])[0].reason, "ambiguous-mapping");
assert.equal(assignmentResults({ assignments: [{ key: "expired", index: 0, value: "深圳市", confidence: 1 }] }, [pageCandidateField])[0].reason, "unknown-field");
console.log("PASS ai-proxy compatibility and profile-path validation");
const certificateChoice = { key: "certificate", isChoice: true, options: ["教师资格证", "其他"], sources: [{ path: "certificates[0].name", value: "大学英语四级" }] };
const fallbackMapping = { assignments: [{ key: "certificate", profilePath: "certificates[0].name", value: "其他", confidence: 0.99 }] };
assert.equal(mappingResults(fallbackMapping, [certificateChoice])[0].reason, "fallback-option-not-source");
assert.equal(mappingResults(fallbackMapping, [{ ...certificateChoice, sources: [{ path: "certificates[0].name", value: "其他" }] }])[0].reason, "accepted");
console.log("PASS explicit source cannot become a generic fallback option");
const awardChoice = { key: "award", label: "奖项名称", module: "获奖信息", isChoice: true,
  options: ["国家奖学金", "国家励志奖学金", "校级一等奖学金", "其他"],
  sources: [{ path: "awards[1].name", value: "优秀学生二等奖学金" }] };
const awardMapping = { assignments: [{ key: "award", profilePath: "awards[1].name", value: "其他", confidence: 0.99 }] };
assert.equal(mappingResults(awardMapping, [awardChoice])[0].reason, "accepted");
assert.equal(mappingResults(awardMapping, [{ ...awardChoice, options: [...awardChoice.options, "优秀学生二等奖学金"] }])[0].reason, "fallback-option-not-source");
assert.equal(mappingResults(awardMapping, [{ ...awardChoice, label: "获奖类型" }])[0].reason, "fallback-option-not-source");
assert.equal(mappingResults({ assignments: [{ ...awardMapping.assignments[0], value: "无" }] }, [{ ...awardChoice, options: ["无"] }])[0].reason, "fallback-option-not-source");
const contestChoice = { ...awardChoice, sources: [{ path: "awards[0].name", value: "广东省蓝桥杯大赛 Web 应用开发组二等奖" }], options: ["蓝桥杯全国软件和信息技术专业人才大赛"] };
assert.equal(mappingResults({ assignments: [{ key: "award", profilePath: "awards[0].name", value: contestChoice.options[0], confidence: 0.99 }] }, [contestChoice])[0].reason, "accepted");
console.log("PASS AI award aliases and scoped other option");
