const assert = require("node:assert/strict");
const fs = require("node:fs");

const source = fs.readFileSync(require.resolve("../popup.js"), "utf8");
const contentSource = fs.readFileSync(require.resolve("../content.js"), "utf8");
const backgroundSource = fs.readFileSync(require.resolve("../background.js"), "utf8");
const mockSource = fs.readFileSync(require.resolve("./mock-form.html"), "utf8");
const manifest = JSON.parse(fs.readFileSync(require.resolve("../manifest.json"), "utf8"));
const profileHelpers = source.slice(0, source.indexOf("function findValue"));
const { cleanProfile } = Function(`${profileHelpers}; return { cleanProfile };`)();
const helpers = source.slice(source.indexOf("function fieldLabel"), source.indexOf("const missingLocalValue"));
const { missingFieldLabels, uniqueEmptyFields, aiFieldContext, fieldsWithLiveOptions, hasProfileContext, localCandidate, localCandidateAssignments, retryFieldKeys, cascadeChildOptions, isCascadeField, cascadeCandidateAssignments, searchableCascadeAssignments, searchableSelectorAssignments, locationSearchHint } = Function(`${helpers}; return { missingFieldLabels, uniqueEmptyFields, aiFieldContext, fieldsWithLiveOptions, hasProfileContext, localCandidate, localCandidateAssignments, retryFieldKeys, cascadeChildOptions, isCascadeField, cascadeCandidateAssignments, searchableCascadeAssignments, searchableSelectorAssignments, locationSearchHint };`)();

const result = missingFieldLabels(["民族", "期望工作城市"], [{ label: "期望工作城市" }]);
assert.deepEqual(result, { unresolved: ["期望工作城市"], unavailable: ["民族"] });
assert.equal(cleanProfile({ awards: [{ name: "奖项", awardDate: "2025-06" }] }).awards[0].date, "2025-06");
assert.equal(cleanProfile({ workExperience: "1年" }).workExperience, "1年");
assert.equal(cleanProfile({ age: 22 }).age, "22");
assert.equal(cleanProfile({ education: [{ "受教育类型": "统招全日制" }] }).education[0].training, "统招全日制");
assert.equal(uniqueEmptyFields([{ key: "page::工作地点::text::0", label: "工作地点", module: "", repeatIndex: 0 }, { key: "page::工作地点::text::1", label: "工作地点", module: "", repeatIndex: 0 }]).length, 2);
assert.deepEqual(uniqueEmptyFields([undefined, { key: "city", label: "期望城市" }]), [{ key: "city", label: "期望城市" }]);
assert.deepEqual(uniqueEmptyFields(), []);
assert.deepEqual(aiFieldContext({ label: "培训机构", module: "培训经历", repeatIndex: 0 }, { jobIntent: { city: "广州" } }), {});
assert.deepEqual(aiFieldContext({ label: "所在地点", module: "个人信息" }, { nativePlace: "广东省汕头市", currentResidence: "广东省广州市" }).locationCandidates, [{ key: "nativePlace", label: "籍贯", value: "广东省汕头市" }, { key: "currentResidence", label: "现居住地", value: "广东省广州市" }]);
assert.equal(aiFieldContext({ label: "所在地点", module: "个人信息" }, { currentResidence: "广东省广州市" }).sourceValue, "广东省广州市");
assert.deepEqual(fieldsWithLiveOptions([{ type: "text", optionSource: "popup", options: ["计算机软件"] }, { type: "radio", optionSource: "radio", options: [] }]), [{ type: "text", optionSource: "popup", options: ["计算机软件"] }]);
assert.deepEqual(fieldsWithLiveOptions([undefined, { options: ["广州"] }]), [{ options: ["广州"] }]);
assert.deepEqual(fieldsWithLiveOptions(), []);
assert.equal(hasProfileContext({ label: "培训地点", module: "培训经历", repeatIndex: 0 }, { jobIntent: { city: "广州" } }), false);
assert.equal(hasProfileContext({ label: "期望工作城市", module: "求职意向" }, { jobIntent: { city: "广州" } }), true);
assert.equal(hasProfileContext({ label: "家乡", module: "个人信息" }, { nativePlace: "广东省汕头市" }), true);
assert.equal(aiFieldContext({ label: "学历类型", module: "教育经历", repeatIndex: 0 }, { education: [{ training: "统招全日制" }] }).sourceValue, "统招全日制");
assert.equal(aiFieldContext({ label: "精通程度", module: "语言能力", repeatIndex: 0 }, { languages: [{ proficiency: "熟练" }] }).sourceValue, "熟练");
assert.equal(localCandidate({ label: "精通程度", module: "语言能力", options: ["入门", "日常会话", "商务会话", "无障碍沟通", "母语"] }, { languages: [{ proficiency: "熟练" }] }), "商务会话");
const candidateProfile = { jobIntent: { industry: "互联网", occupation: "前端开发", expectedSalary: "3500", city: "广州市" }, work: [{ location: "广州市" }, { location: "深圳市" }] };
assert.equal(localCandidate({ label: "期望从事行业", options: ["制造业", "互联网/电子商务"] }, candidateProfile), "互联网/电子商务");
assert.equal(localCandidate({ label: "期望从事行业", options: ["制造业", "互联网/电子商务"] }, { jobIntent: { industry: "互联网行业" } }), "互联网/电子商务");
assert.equal(localCandidate({ label: "期望从事职业", options: ["Java开发工程师", "Web前端开发工程师"] }, { jobIntent: { occupation: "前端工程" } }), "Web前端开发工程师");
assert.equal(localCandidate({ label: "期望月薪(税前)", options: ["2001～4000", "8001～10000"] }, candidateProfile), "2001～4000");
assert.equal(localCandidate({ label: "工作地点", module: "工作经历", repeatIndex: 1, options: ["广州", "深圳"] }, candidateProfile), "深圳");
assert.equal(aiFieldContext({ label: "工作地点", module: "", repeatIndex: 0, occurrence: 1 }, candidateProfile).experience.location, "深圳市");
assert.equal(locationSearchHint({ label: "工作地点", module: "工作经历", repeatIndex: 0 }, { work: [{ location: "广东省", company: "广州市示例公司" }] }), "广州市");
assert.equal(locationSearchHint({ label: "工作地点", module: "工作经历", repeatIndex: 0 }, { work: [{ location: "广东省", company: "广州示例公司" }] }), "广州");
assert.equal(localCandidate({ label: "期望从事职业", options: ["前端开发工程师", "前端开发实习生"] }, candidateProfile), "");
assert.deepEqual(localCandidateAssignments([{ key: "city", index: 2, label: "期望工作城市", options: ["广州", "深圳"] }], candidateProfile), [{ key: "city", index: 2, label: "期望工作城市", value: "广州", confidence: 1 }]);
assert.deepEqual(localCandidateAssignments([{ key: "city", index: 2, label: "期望工作城市", options: ["广东省", "浙江省"] }], candidateProfile), []);
assert.deepEqual(localCandidateAssignments([{ key: "city", index: 2, label: "工作地点", module: "工作经历", repeatIndex: 0, options: ["广东省", "广州市"] }], candidateProfile), [{ key: "city", index: 2, label: "工作地点", value: "广州市", confidence: 1 }]);
assert.deepEqual(cascadeChildOptions(["广东省", "广州市", "深圳市"], new Set(["广东省"])), ["广州市", "深圳市"]);
assert.equal(isCascadeField({ label: "期望从事行业", optionSource: "popup" }), true);
assert.equal(isCascadeField({ label: "期望从事行业", optionSource: "popup", hasSearch: true, hasConfirmation: true, isMultiSelector: true }), true);
assert.equal(isCascadeField({ label: "工作地点", optionSource: "popup", hasSearch: true, hasConfirmation: true, isMultiSelector: true }), false);
assert.equal(isCascadeField({ label: "期望从事职业", optionSource: "popup" }), true);
assert.equal(isCascadeField({ label: "自定义分类", optionSource: "popup", hasConfirmation: true }), true);
assert.equal(isCascadeField({ label: "期望从事行业", optionSource: "native" }), false);
assert.deepEqual(cascadeCandidateAssignments([
  { key: "work-1", index: 1, label: "工作地点", module: "工作经历", repeatIndex: 0, optionSource: "popup", options: ["广东省", "浙江省"] },
  { key: "work-2", index: 2, label: "工作地点", module: "工作经历", repeatIndex: 1, optionSource: "popup", options: ["广东省", "浙江省"] }
], { work: [{ location: "广东省广州市" }, { location: "浙江省杭州市" }] }).map(({ key, value, directLocationSearch }) => ({ key, value, directLocationSearch })), [{ key: "work-1", value: "广东省广州市", directLocationSearch: true }, { key: "work-2", value: "浙江省杭州市", directLocationSearch: true }]);
assert.deepEqual(cascadeCandidateAssignments([{ key: "ambiguous", index: 0, label: "期望从事职业", optionSource: "popup", options: ["前端开发工程师", "前端开发实习生"] }], candidateProfile), []);
assert.deepEqual(searchableCascadeAssignments([{ key: "industry", index: 0, label: "期望从事行业", hasSearch: true }], candidateProfile).map(({ key, value }) => ({ key, value })), [{ key: "industry", value: "互联网" }]);
assert.deepEqual(searchableCascadeAssignments([{ key: "city", index: 0, label: "期望工作城市", hasSearch: true, isMultiSelector: true }], candidateProfile), []);
assert.deepEqual(searchableCascadeAssignments([{ key: "industry", index: 0, label: "期望从事行业", hasSearch: true, isMultiSelector: true }], candidateProfile).map(({ key, value }) => ({ key, value })), [{ key: "industry", value: "互联网" }]);
assert.deepEqual(searchableCascadeAssignments([{ key: "work-city", index: 0, label: "工作地点", module: "工作经历", repeatIndex: 0, hasSearch: true }], candidateProfile).map(({ key, value, directLocationSearch }) => ({ key, value, directLocationSearch })), [{ key: "work-city", value: "广州市", directLocationSearch: true }]);
assert.deepEqual(searchableSelectorAssignments([{ key: "industry", index: 0, label: "期望从事行业", hasSearch: true, isMultiSelector: true, options: ["制造业", "互联网/电子商务"] }], candidateProfile), []);
assert.deepEqual([...retryFieldKeys([{ key: "city", optionSource: "popup", options: [] }], 1)], ["city"]);
assert.deepEqual([...retryFieldKeys([undefined, { key: "city", optionSource: "popup", options: [] }], 1)], ["city"]);
assert.deepEqual([...retryFieldKeys(undefined, 1)], []);
assert.deepEqual([...retryFieldKeys([], 0)], []);
const choiceStepSource = source.slice(source.indexOf("const choiceStep ="), source.indexOf("const awardChoice ="));
const { choiceStep } = Function(`${choiceStepSource}; return { choiceStep };`)();
assert.doesNotThrow(() => choiceStep(null, "年"));
const selectionTargetSource = contentSource.slice(contentSource.indexOf("const selectionTarget ="), contentSource.indexOf("const choiceState ="));
const { selectionTarget } = Function(`${selectionTargetSource}; return { selectionTarget };`)();
const areaIcon = {};
const areaRow = { querySelector: () => areaIcon };
assert.equal(selectionTarget({ closest: (selector) => selector.includes("area-item-container") ? areaRow : null }), areaIcon);
assert.doesNotMatch(source, /forceMatch/);
assert.match(source, /body: JSON\.stringify\(\{ profile, fields: aiFields \}\)/);
assert.match(source, /const liveFields = fieldsWithLiveOptions\(scannedFields\)/);
assert.match(source, /cascade-parent-selected/);
assert.match(source, /keepOpen: true/);
assert.match(source, /for \(const initial of cascadeAssignments\)/);
assert.match(source, /level <= 6/);
assert.match(source, /keys: \[assignment\.key\], keepOpen: true/);
assert.match(source, /const sourceValue = field\?\.profileContext\?\.sourceValue/);
assert.match(source, /\["ai-no-assignment", "not-a-page-option", "candidate-not-read", "options-unavailable"\]/);
assert.match(source, /chrome\.scripting\.executeScript/);
assert.match(source, /CONTENT_MESSAGE_SUFFIX = "_V60"/);
assert.match(contentSource, /__resumeAutofillContentProtocol/);
assert.match(contentSource, /CONTENT_PROTOCOL = 60/);
assert.match(source, /"受教育类型"/);
assert.match(backgroundSource, /type: "mousePressed", x, y, button: "left", buttons: 1/);
assert.match(contentSource, /rect\.width > 0 && rect\.height > 0/);
assert.match(contentSource, /only trust the debugger click after the tree actually expands/);
assert.match(contentSource, /atsx-tree-switcher/);
assert.match(contentSource, /bounded virtual-tree scan/);
assert.match(contentSource, /selectionAttempts/);
assert.match(contentSource, /record\.trusted/);
assert.match(contentSource, /const areaText = \(node\) => clean\(node\?\.innerText \|\| node\?\.textContent\)/);
assert.match(contentSource, /\.atsx-tree-node-content-wrapper/);
assert.match(contentSource, /const displaySelected =/);
assert.match(contentSource, /const treeCity =/);
assert.match(contentSource, /const isAtsxTree = !!areaPopup\.querySelector/);
assert.match(contentSource, /#id-card-select-component/);
assert.match(contentSource, /atsx-date-picker-period-month-label/);
assert.match(contentSource, /atsx-year-picker/);
assert.match(contentSource, /"获奖名称"/);
assert.match(contentSource, /atsx-period-month/);
assert.match(contentSource, /\.createFormSection-repeatable/);
assert.match(contentSource, /\.resumeEditForm-item/);
assert.match(mockSource, /ui === "atsx"/);
assert.match(mockSource, /#id-card-select-component/);
assert.match(mockSource, /#projectRows \.resumeEditForm-item/);
assert.match(mockSource, /#internshipRows \.resumeEditForm-item/);
assert.match(contentSource, /: \[selectionTarget\(city\)\]/);
assert.match(contentSource, /if \(!isAtsxTree\) return \[\.\.\.areaPopup\.querySelectorAll/);
assert.match(contentSource, /normalize\(el\.textContent\)\.endsWith\(normalize\(name\)\)/);
assert.match(contentSource, /for \(const term of citySearchTerms\)/);
assert.match(contentSource, /cityPart\.replace\(/);
assert.match(contentSource, /const cityPart = location\?\.\[2\]/);
assert.match(contentSource, /controlBox\]\.flatMap/);
assert.match(contentSource, /for \(const cityTarget of cityTargets\)/);
assert.match(contentSource, /await clickOption\(cityTarget, true, null, attempt\);/);
assert.match(contentSource, /waitFor\(selectionChanged, 1500\)/);
assert.match(contentSource, /!isLocationPicker/);
assert.match(contentSource, /area-city-not-found/);
assert.match(contentSource, /trace\.area = \{ protocol: CONTENT_PROTOCOL/);
assert.match(source, /地区协议 V\$\{area\.protocol/);
assert.match(source, /locationSearchHint/);
assert.match(contentSource, /chooseOptions\.locationHint/);
assert.match(contentSource, /const companyHint/);
assert.match(contentSource, /clickOption\(commitTarget, multiSelector, multiSelector \? selectionChanged : null\)/);
assert.match(contentSource, /!readControl\(\) && !\(multiSelector && trace\.selectionObserved\)/);
assert.match(contentSource, /\[\.\.\.new Set\(\[popup, \.\.\.popupFor\(control\)\]\)\]/);
assert.match(contentSource, /const waitForAreaResult = async/);
assert.match(contentSource, /queryResults\.push/);
assert.match(contentSource, /result\.settled && result\.count/);
assert.match(source, /searchableSelectorAssignments/);
assert.match(contentSource, /isMultiSelector/);
assert.match(contentSource, /list-item-container/);
assert.match(contentSource, /area-item-container/);
assert.match(source, /!field\.isMultiSelector/);
assert.match(contentSource, /commitTarget/);
assert.match(contentSource, /const commitTarget = selectionTarget\(option\)/);
assert.doesNotMatch(contentSource, /chooseOptions\.deferConfirm \? option/);
assert.match(contentSource, /RESUME_AUTOFILL_TRUSTED_CLICK/);
assert.match(contentSource, /selectionObserved/);
assert.match(contentSource, /confirmAttempted/);
assert.match(contentSource, /multiCommitted/);
assert.match(contentSource, /!actualDate\[2\] \|\| actualDate\[2\] === expectedDate\[2\]/);
assert.match(contentSource, /type\.endsWith\(suffix\)/);
assert.match(contentSource, /writeAndObserveSuggestion/);
assert.match(contentSource, /\["项目链接", "link"\]/);
assert.match(contentSource, /isSuggestionControl/);
assert.match(contentSource, /pointerdown/);
assert.match(contentSource, /a, button, \[role=button\]/);
assert.match(contentSource, /trace\.optionFound/);
assert.doesNotMatch(contentSource, /lastChoice\.optionFound/);
assert.match(contentSource, /semantic\.length \? semantic : leaves/);
assert.doesNotMatch(contentSource, /setSearchValue\(sourceSearch, sourceValue\)/);
assert.match(source, /childOptionsUpdated/);
assert.match(source, /confirmedValue/);
assert.match(contentSource, /popupFor\(dateControl, false\)/);
assert.match(source, /协议 \$\{picker\.protocol \? `V\$\{picker\.protocol\}` : "旧版"\}/);
assert.ok(manifest.permissions.includes("scripting"));
assert.ok(manifest.permissions.includes("debugger"));
assert.match(backgroundSource, /chrome\.debugger\.attach/);
assert.match(backgroundSource, /Input\.dispatchMouseEvent/);
assert.match(backgroundSource, /sender\.id !== chrome\.runtime\.id/);
console.log("PASS popup diagnostics");
